### ISSUE TITLE
Status of this repository

### ISSUE THREAD

**Issue by championshuttler** [mozilla/community-data#17]
I think this repo is not updated for a while.
I filled the google form listed on about:credits, but did not get any response till now.

Thanks

**Comment by gurumukhi** [comment]
Let me check it right away, will update here once this is done.

**Comment by gurumukhi** [comment]
Updated the names as per policy (https://www.mozilla.org/credits/faq/).

**Comment by championshuttler** [comment]
@gurumukhi do i need to submit the form again as i submitted a long ago?

**Comment by gurumukhi** [comment]
As per the Mozilla policy "If your application does not meet the criteria mentioned above, your name will not be added. You are always welcome to re-apply once you have a stronger citation and further evidence."

**Comment by twse** [comment]
I filled the Google Docs form to add Julius Schwartzenberg to credits list but his name did not appear in the credits list. All other Dutch localizers are missing: Samir Boulema, Arjen Eerden, Stefan Livens, Paul H. Oranje, Mark Tetrode, Rene van Roon and Paul Wagenaars.
