### ISSUE TITLE
Update my name on the credit page.

### ISSUE THREAD

**Issue by kuoe0** [mozilla/community-data#36]
Hi, I'm Tommy Kuo. Because I prefer using my real name, Chih-Hsuan Kuo, rather than Tommy Kuo, I'd like to change my name that is shown on https://www.mozilla.org/credits/. Thanks!

**Comment by shahbaz17** [comment]
Name updated!

Now your real name is live on https://www.mozilla.org/credits/ https://github.com/mozilla/community-data/commit/c259b435f233fb5c61540b1651494d4a44040f9f 🎉 

Thanks @kuoe0
