### ISSUE TITLE
Processing pending names

### ISSUE THREAD

**Issue by gurumukhi** [mozilla/community-data#41]
Due to pandemic & other reasons names are not being updated from some time. Lets discuss about processing pending names here & put other related updates here.

**Comment by gurumukhi** [comment]
We will try to process all the names by this weekend into batches. As part of our process, I have sent mail to 301 accepted applicants of first batch.

**Comment by plwt** [comment]
Not all of those names should have been written to yet - it is only supposed to be the oldest 250 names that I have looked at as I had previously confirmed.

**Comment by gurumukhi** [comment]
As per discussion with @plwt & others, we have initiated process for processing first 400 names. We have sent email to accepted applicants, but because of some issues with getting the script running its slightly delayed. We are trying to get it done within this weel.

**Comment by gurumukhi** [comment]
Added 291 names via https://github.com/mozilla/community-data/pull/42. Thanks a lot @imjenal for stepping up to help here.

Process for second batch (containing around 400 rows) is under process, we are expecting to finish it by next week. Will update here accordingly.

**Comment by plwt** [comment]
We are not ready to process the second batch yet - we still have a lot of names still to check.  Everything above row 2699 is ready to go.  

There are still about 200 names to check before we can process the second batch.

**Comment by plwt** [comment]
All names are now ready to be emailed and processed!

Important - Please be careful with row 2875 - this is a correction to an existing record.

**Comment by gurumukhi** [comment]
This exercise is done now. Thanks everyone for stepping in and clear the backlog.
